# OpenAPIのバージョンを指定
openapi: 3.0.3

# APIの基本情報
info:
  title: シンプルなユーザーAPI
  description: ユーザー情報を取得するためのサンプルAPIです。
  version: 1.0.0
  contact:
    name: APIサポート
    email: support@example.com

# APIサーバーの情報
servers:
  - url: https://api.example.com/v1
    description: 本番環境サーバー

# APIのパスと操作を定義
paths:
  /users/{userId}:
    get:
      summary: ユーザー情報を取得
      description: 指定されたIDのユーザー情報を返します。
      tags:
        - User
      parameters:
        - name: userId
          in: path
          description: 取得するユーザーのID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功時のレスポンス
          content:
            application/json:
              schema:
                # componentsで定義したUserスキーマを参照
                $ref: '#/components/schemas/User'
        '404':
          description: ユーザーが見つからない

# 再利用可能なコンポーネントを定義
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: 山田 太郎
        email:
          type: string
          format: email
          example: taro.yamada@example.com